# https://github.com/CircleCI-Public/aws-ecr-orb
# https://circleci.com/docs/2.0/workflows/#git-tag-job-execution
# ENV VARS
# AWS_ACCESS_KEY_ID
# AWS_SECRET_ACCESS_KEY
# AWS_ECR_ACCOUNT_URL
# AWS_ECR_REPO_NAME
# AWS_REGION_NAME
# semver regex \bv?(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)(?:-[\da-z-]+(?:\.[\da-z-]+)*)?(?:\+[\da-z-]+(?:\.[\da-z-]+)*)?\b
# ###### Matches: v1.2.2-rc.2, v1.2.2, etc.
version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@3.0.0

jobs:
  get:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
        command: |
          TAG_VERSION=$(git describe --abbrev=0)
          $TAG_VERSION
        name: Get latest tag from branch

workflows:
  version: 2
  tagged-builds:
    jobs:
      - get_tag
      - aws-ecr/build_and_push_image:
          repo: ${AWS_ECR_REPO_NAME}
          tag: ${TAG_VERSION}
          # filters:
          #   branches:
          #     ignore: /.*/
          #   tags:
          #     only: /\bv?(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)(?:-[\da-z-]+(?:\.[\da-z-]+)*)?(?:\+[\da-z-]+(?:\.[\da-z-]+)*)?\b/
