version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@3.0.0

executors:
  build-executor:
    docker:
      - image: buildpack-deps:jessie

jobs:
  approval:
    executor: build-executor
    steps:
      - checkout
      - run:
          name: Get latest tag from branch
          command: TAG_VERSION=$(git describe --abbrev=0)

workflows:
  version: 2
  tagged-builds:
    jobs:
      - approved-build:
          type: approval
      - aws-ecr/build_and_push_image:
          repo: ${AWS_ECR_REPO_NAME}
          tag: ${CIRCLE_TAG}
          requires:
            - approved-build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /\bv?(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)(?:-[\da-z-]+(?:\.[\da-z-]+)*)?(?:\+[\da-z-]+(?:\.[\da-z-]+)*)?\b/

          



# jobs:
#   get_tag:
#     executor: build-executor
#     steps:
#       - checkout
#       - run:
#           name: Get latest tag from branch
#           command: TAG_VERSION=$(git describe --abbrev=0)
